### ISSUE TITLE
Dies to PR #27509

### ISSUE THREAD

**Issue by juippis** [mgorny/dev2github#3]
```
PR #27509
https://github.com/gentoo/gentoo/pull/27509
https://github.com/gentoo/gentoo/pull/27509.patch
PR submitter (NamedUser(login="stwnt")) != committer (NamedUser(login="invalid-email-address"))
Traceback (most recent call last):
  File "/home/joonas/git/dev2github/./update-pr-submitter-db.py", line 82, in <module>
    sys.exit(main(*sys.argv[1:]))
  File "/home/joonas/git/dev2github/./update-pr-submitter-db.py", line 55, in main
    c1.commit.committer.name, attributed.login, attributed.name))
  File "/usr/lib/python3.10/site-packages/github/NamedUser.py", line 276, in name
    self._completeIfNotSet(self._name)
  File "/usr/lib/python3.10/site-packages/github/GithubObject.py", line 297, in _completeIfNotSet
    self._completeIfNeeded()
  File "/usr/lib/python3.10/site-packages/github/GithubObject.py", line 301, in _completeIfNeeded
    self.__complete()
  File "/usr/lib/python3.10/site-packages/github/GithubObject.py", line 308, in __complete
    headers, data = self._requester.requestJsonAndCheck("GET", self._url.value)
  File "/usr/lib/python3.10/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/usr/lib/python3.10/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/users#get-a-user"}
```

For now I've added the username on to `if pr.user.login in` array until I got past this PR, then removed it.

**Comment by juippis** [comment]
Tested and it works. Thank you!

**Comment by mgorny** [comment]
Thanks!
